name = "dg-timing-app"
compatibility_date = "2026-08-26"
main = "worker.js"

[[d1_databases]]
binding = "DB"
database_name = "dg-timing"
database_id = "6517a5ec-fa14-4789-8845-1873b72b579c"

[vars]
APP_ORIGIN = "https://discgolftiming.com"
SENDER_EMAIL = "Disc Golf Timing <no-reply@discgolftiming.com>"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true
not_found_handling = "404-page"

[observability]
enabled = false
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
